### ISSUE TITLE
Release 2.0.0 FastAuthWallet version to BOS VM and NearDiscovery

### ISSUE THREAD

**Issue by Pessina** [near/fast-auth-signer#249]
The current FastAuthWallet and FastAuthSigner support only signing delegate actions. This PR introduces new methods to enable FastAuthWallet and FastAuthSigner to sign and send transactions without using a relayer.

PR link: [#26](https://github.com/near/near-fastauth-wallet/pull/26)

## New Methods:

- `signAndSendSignedDelegate`
- `signAndSendTransaction`

The interface of these new methods is consistent with the existing `signAndSendTransaction`.

## Important Notes:

- This release is a breaking change.
- To access the new features, update to wallet version 2.0.0.
- Post-merge, update BOS VM and Near Discovery to use the latest wallet version.

**Comment by charleslavon** [comment]
hey @Pessina can you help clarify what are the end goals as it relates to [near-discovery](https://github.com/near/near-discovery/blob/develop/package.json#L58) and the [relayer used by the vm](https://github.com/near/near-discovery/blob/5f0012d9dd7e389f9eecf6c8c38139b3835f5aa6/src/components/vm/VmInitializer.tsx#L98)

**Comment by Pessina** [comment]
Hey @charleslavon , 

The previous version of the wallet was only able to sign DelegateAction and send them through the relayer. What imposed some limitations, like: only being able to call contracts and actions whitelisted/allowed by the relayer. 

With this new version, the dApp have the option to choose if it wants to request a DelegateAction signature (gas paid by the relayer) or a Transaction signature (gas paid by the user). 

For more details I pinged @esaminu, I think he knows more about the ecosystem and can explain it better than me.

**Comment by esaminu** [comment]
Hi @charleslavon to add to @Pessina 's explanation the end goal is to integrate the new `signAndSendDelegateAction` into the BOS and make it accessible to component developers. Currently only `signAndSendTransaction` is accessible to component devs through the following methods:
1. [`Social.set`](https://docs.near.org/build/near-components/anatomy/social#socialset)
2. [`Near.call`](https://docs.near.org/build/near-components/anatomy/near#nearcall)
3. `CommitButton`, I remember using this before but I don't see it in the docs anymore. Maybe it was deprecated?

We need to add similar methods or add additional arguments to these methods so that component developers can be more explicit and opt to send these transactions as meta transactions covered by the relayer and secondly we need to update the actions that intend to use the relayer in  [near-discovery-components](https://github.com/near/near-discovery-components) e.g. the TOS component and DevHub components. Since BOS components support many wallets they will likely need to check if the wallet their user selected supports meta transactions before calling the new methods.

**Comment by geltonastech** [comment]
Just to understand. So people like me who created a wallet using email address at near.org still cannot withdraw funds right? 

how to create a ticket for help in this regard? thanks in advance

**Comment by charleslavon** [comment]
hey @geltonastech this issue is a requisite to support allowing fast-auth accounts successfully sign arbitrary transactions like sending funds. This is being prioritized for attention. Keep an eye on this issue for progress updates. Thanks.

**Comment by charleslavon** [comment]
@Pessina @esaminu for local development and testing of `2.1.0`, what should I pass into `setupFastAuthWallet({ walletUrl, iconUrl, deprecated, successUrl, failureUrl, relayerUrl, })`

**Comment by Pessina** [comment]
@charleslavon for local development you have to provide the `walletUrl`. If the relayer it's failing too much, I also provide the `relayerUrl`. 

In order to provide the `walletUrl` follow this steps: 

- Clone https://github.com/near/fast-auth-signer
- Install dependencies `yarn install`
- Navigate to `packages/near-fast-auth-signer`
- Run `NETWORK_ID=testnet yarn start`
- Usually it will run on port 3000

Then you provide to `walletUrl: http://localhost:3000` something like this. 

Let me know if you face any issues, if it's better you can ping me on slack

**Comment by Pessina** [comment]
@charleslavon I'm sorry, I think I wasn't clear about the `relayerUrl`, you have to provide it.

In case the url setup on the main branch it's not working, then I provide a local `relayerUrl`

**Comment by charleslavon** [comment]
@geltonastech See the instructions [here](https://nearhelp.zendesk.com/hc/en-us/articles/24739838024599-How-to-Transfer-NEAR-Tokens-Using-FastAuthWallet-and-FastAuthSigner)

**Comment by geltonastech** [comment]
Lots of thanks charles ! I just solved the issue. thanks again you all for your time ))

**Comment by calebjacob** [comment]
Hey @esaminu, thanks for being willing to help me debug the relayer issues I mentioned in Slack. Getting everything running is going to be a bit of a chore because the changes need to be made in the [VM layer](https://github.com/NearSocial/VM), but here are the steps to follow in order:

1. Clone or pull the latest changes for the gateway (on the `develop` branch): https://github.com/near/near-discovery
2. Clone my fork of the VM repo and checkout the `dev` branch: https://github.com/calebjacob/VM/tree/dev
3. Check out this README section for the rest of the steps: https://github.com/near/near-discovery?tab=readme-ov-file#local-vm-development
4. Open up the local gateway at `localhost:3000` and sign in to any FastAuth account
5. You should see our TOS modal pop up. Attempting to accept the TOS will trigger the 500 response from the relayer.
6. Refresh the page to trigger the TOS modal again and repeat as needed.

Here's a quick Loom going over what I'm seeing: https://www.loom.com/share/c3a4e67b6c254fa298b9cbd76f5c55e6

**Comment by calebjacob** [comment]
@esaminu I forgot to mention where my relevant code changes are in my VM fork. Here's a screenshot (`src/lib/data/commitData.js`):

<img width="1502" alt="Screenshot 2024-07-09 at 3 54 28 PM" src="https://github.com/near/fast-auth-signer/assets/1475067/816a73c6-2c7f-49d5-bcfd-c47b99958c8c">

**Comment by calebjacob** [comment]
Hey @charleslavon, I've opened a PR to merge into the official VM repo here: https://github.com/NearSocial/VM/pull/200
